# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/yc/code/calibre/calibre/src/calibre/gui2/catalog/catalog_epub_mobi.ui'
#
# Created: Thu Oct 25 16:54:55 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(658, 603)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setWindowTitle(_("Form"))
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.includedSections = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.includedSections.sizePolicy().hasHeightForWidth())
        self.includedSections.setSizePolicy(sizePolicy)
        self.includedSections.setMinimumSize(QtCore.QSize(0, 0))
        self.includedSections.setToolTip(_("Enabled sections will be included in the generated catalog."))
        self.includedSections.setTitle(_("Included sections"))
        self.includedSections.setObjectName(_fromUtf8("includedSections"))
        self.gridLayout_2 = QtGui.QGridLayout(self.includedSections)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.generate_authors = QtGui.QCheckBox(self.includedSections)
        self.generate_authors.setEnabled(True)
        self.generate_authors.setText(_("&Authors"))
        self.generate_authors.setChecked(False)
        self.generate_authors.setObjectName(_fromUtf8("generate_authors"))
        self.gridLayout_2.addWidget(self.generate_authors, 0, 0, 1, 1)
        self.generate_titles = QtGui.QCheckBox(self.includedSections)
        self.generate_titles.setText(_("&Titles"))
        self.generate_titles.setObjectName(_fromUtf8("generate_titles"))
        self.gridLayout_2.addWidget(self.generate_titles, 0, 2, 1, 1)
        self.generate_series = QtGui.QCheckBox(self.includedSections)
        self.generate_series.setText(_("&Series"))
        self.generate_series.setObjectName(_fromUtf8("generate_series"))
        self.gridLayout_2.addWidget(self.generate_series, 0, 3, 1, 1)
        self.generate_genres = QtGui.QCheckBox(self.includedSections)
        self.generate_genres.setText(_("&Genres"))
        self.generate_genres.setObjectName(_fromUtf8("generate_genres"))
        self.gridLayout_2.addWidget(self.generate_genres, 4, 0, 1, 1)
        self.generate_recently_added = QtGui.QCheckBox(self.includedSections)
        self.generate_recently_added.setText(_("&Recently Added"))
        self.generate_recently_added.setObjectName(_fromUtf8("generate_recently_added"))
        self.gridLayout_2.addWidget(self.generate_recently_added, 4, 2, 1, 1)
        self.generate_descriptions = QtGui.QCheckBox(self.includedSections)
        self.generate_descriptions.setText(_("&Descriptions"))
        self.generate_descriptions.setObjectName(_fromUtf8("generate_descriptions"))
        self.gridLayout_2.addWidget(self.generate_descriptions, 4, 3, 1, 1)
        self.verticalLayout.addWidget(self.includedSections)
        self.prefix_rules_gb = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prefix_rules_gb.sizePolicy().hasHeightForWidth())
        self.prefix_rules_gb.setSizePolicy(sizePolicy)
        self.prefix_rules_gb.setToolTip(_("The first matching prefix rule applies a prefix to book listings in the generated catalog."))
        self.prefix_rules_gb.setTitle(_("Prefixes"))
        self.prefix_rules_gb.setObjectName(_fromUtf8("prefix_rules_gb"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.prefix_rules_gb)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.horizontalLayout_8.addLayout(self.horizontalLayout_6)
        self.verticalLayout.addWidget(self.prefix_rules_gb)
        self.exclusion_rules_gb = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exclusion_rules_gb.sizePolicy().hasHeightForWidth())
        self.exclusion_rules_gb.setSizePolicy(sizePolicy)
        self.exclusion_rules_gb.setMinimumSize(QtCore.QSize(0, 0))
        self.exclusion_rules_gb.setToolTip(_("Books matching any of the exclusion rules will be excluded from the generated catalog. "))
        self.exclusion_rules_gb.setTitle(_("Excluded books"))
        self.exclusion_rules_gb.setObjectName(_fromUtf8("exclusion_rules_gb"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.exclusion_rules_gb)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.exclusion_rules_gb)
        self.excludedGenres = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.excludedGenres.sizePolicy().hasHeightForWidth())
        self.excludedGenres.setSizePolicy(sizePolicy)
        self.excludedGenres.setMinimumSize(QtCore.QSize(0, 0))
        self.excludedGenres.setToolTip(_("A regular expression describing genres to be excluded from the generated catalog. Genres are derived from the tags applied to your books.\n"
"The default pattern \\[.+\\]|\\+ excludes tags of the form [tag], e.g., [Test book], and \'+\', the default tag for a read book."))
        self.excludedGenres.setTitle(_("Excluded genres"))
        self.excludedGenres.setObjectName(_fromUtf8("excludedGenres"))
        self.gridLayout = QtGui.QGridLayout(self.excludedGenres)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.excludedGenres)
        self.label.setMinimumSize(QtCore.QSize(175, 0))
        self.label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label.setText(_("Tags to &exclude (regex):"))
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.exclude_genre = QtGui.QLineEdit(self.excludedGenres)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exclude_genre.sizePolicy().hasHeightForWidth())
        self.exclude_genre.setSizePolicy(sizePolicy)
        self.exclude_genre.setMinimumSize(QtCore.QSize(0, 0))
        self.exclude_genre.setToolTip(_fromUtf8(""))
        self.exclude_genre.setObjectName(_fromUtf8("exclude_genre"))
        self.gridLayout.addWidget(self.exclude_genre, 0, 1, 1, 1)
        self.reset_exclude_genres_tb = QtGui.QToolButton(self.excludedGenres)
        self.reset_exclude_genres_tb.setToolTip(_("Reset to default"))
        self.reset_exclude_genres_tb.setText(_("..."))
        self.reset_exclude_genres_tb.setObjectName(_fromUtf8("reset_exclude_genres_tb"))
        self.gridLayout.addWidget(self.reset_exclude_genres_tb, 0, 2, 1, 1)
        self.regex_results_label = QtGui.QLabel(self.excludedGenres)
        self.regex_results_label.setMinimumSize(QtCore.QSize(175, 0))
        self.regex_results_label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.regex_results_label.setText(_("Results of regex:"))
        self.regex_results_label.setTextFormat(QtCore.Qt.AutoText)
        self.regex_results_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.regex_results_label.setWordWrap(True)
        self.regex_results_label.setObjectName(_fromUtf8("regex_results_label"))
        self.gridLayout.addWidget(self.regex_results_label, 1, 0, 1, 1)
        self.exclude_genre_results = QtGui.QLabel(self.excludedGenres)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exclude_genre_results.sizePolicy().hasHeightForWidth())
        self.exclude_genre_results.setSizePolicy(sizePolicy)
        self.exclude_genre_results.setMinimumSize(QtCore.QSize(0, 0))
        self.exclude_genre_results.setToolTip(_("Tags that will be excluded as genres"))
        self.exclude_genre_results.setFrameShape(QtGui.QFrame.StyledPanel)
        self.exclude_genre_results.setText(_fromUtf8(""))
        self.exclude_genre_results.setTextFormat(QtCore.Qt.PlainText)
        self.exclude_genre_results.setWordWrap(True)
        self.exclude_genre_results.setObjectName(_fromUtf8("exclude_genre_results"))
        self.gridLayout.addWidget(self.exclude_genre_results, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.excludedGenres)
        self.otherOptions = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.otherOptions.sizePolicy().hasHeightForWidth())
        self.otherOptions.setSizePolicy(sizePolicy)
        self.otherOptions.setMinimumSize(QtCore.QSize(0, 0))
        self.otherOptions.setTitle(_("Other options"))
        self.otherOptions.setObjectName(_fromUtf8("otherOptions"))
        self.gridLayout_3 = QtGui.QGridLayout(self.otherOptions)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.merge_with_comments_hl = QtGui.QHBoxLayout()
        self.merge_with_comments_hl.setObjectName(_fromUtf8("merge_with_comments_hl"))
        self.merge_source_field = QtGui.QComboBox(self.otherOptions)
        self.merge_source_field.setMinimumSize(QtCore.QSize(0, 0))
        self.merge_source_field.setToolTip(_("Custom column containing additional content to be merged with Comments metadata."))
        self.merge_source_field.setObjectName(_fromUtf8("merge_source_field"))
        self.merge_with_comments_hl.addWidget(self.merge_source_field)
        self.line_2 = QtGui.QFrame(self.otherOptions)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.merge_with_comments_hl.addWidget(self.line_2)
        self.merge_before = QtGui.QRadioButton(self.otherOptions)
        self.merge_before.setToolTip(_("Merge additional content before Comments metadata."))
        self.merge_before.setText(_("&Before"))
        self.merge_before.setObjectName(_fromUtf8("merge_before"))
        self.merge_options_bg = QtGui.QButtonGroup(Form)
        self.merge_options_bg.setObjectName(_fromUtf8("merge_options_bg"))
        self.merge_options_bg.addButton(self.merge_before)
        self.merge_with_comments_hl.addWidget(self.merge_before)
        self.merge_after = QtGui.QRadioButton(self.otherOptions)
        self.merge_after.setToolTip(_("Merge additional content after Comments metadata."))
        self.merge_after.setText(_("&After"))
        self.merge_after.setObjectName(_fromUtf8("merge_after"))
        self.merge_options_bg.addButton(self.merge_after)
        self.merge_with_comments_hl.addWidget(self.merge_after)
        self.line = QtGui.QFrame(self.otherOptions)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.merge_with_comments_hl.addWidget(self.line)
        self.include_hr = QtGui.QCheckBox(self.otherOptions)
        self.include_hr.setToolTip(_("Separate Comments metadata and additional content with a horizontal rule."))
        self.include_hr.setText(_("Include &Separator"))
        self.include_hr.setObjectName(_fromUtf8("include_hr"))
        self.merge_with_comments_hl.addWidget(self.include_hr)
        self.gridLayout_3.addLayout(self.merge_with_comments_hl, 2, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.otherOptions)
        self.label_9.setMinimumSize(QtCore.QSize(175, 0))
        self.label_9.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_9.setText(_("&Merge with Comments:"))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.otherOptions)
        self.label_4.setMinimumSize(QtCore.QSize(175, 20))
        self.label_4.setText(_("Catalog cover:"))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.replace_cover_hl = QtGui.QHBoxLayout()
        self.replace_cover_hl.setObjectName(_fromUtf8("replace_cover_hl"))
        self.generate_new_cover = QtGui.QRadioButton(self.otherOptions)
        self.generate_new_cover.setText(_("Generate new cover"))
        self.generate_new_cover.setChecked(True)
        self.generate_new_cover.setObjectName(_fromUtf8("generate_new_cover"))
        self.cover_options_bg = QtGui.QButtonGroup(Form)
        self.cover_options_bg.setObjectName(_fromUtf8("cover_options_bg"))
        self.cover_options_bg.addButton(self.generate_new_cover)
        self.replace_cover_hl.addWidget(self.generate_new_cover)
        self.use_existing_cover = QtGui.QRadioButton(self.otherOptions)
        self.use_existing_cover.setText(_("Use existing cover"))
        self.use_existing_cover.setObjectName(_fromUtf8("use_existing_cover"))
        self.cover_options_bg.addButton(self.use_existing_cover)
        self.replace_cover_hl.addWidget(self.use_existing_cover)
        self.spacer_label = QtGui.QLabel(self.otherOptions)
        self.spacer_label.setText(_fromUtf8(""))
        self.spacer_label.setObjectName(_fromUtf8("spacer_label"))
        self.replace_cover_hl.addWidget(self.spacer_label)
        self.gridLayout_3.addLayout(self.replace_cover_hl, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.otherOptions)
        self.label_3.setText(_("E&xtra Description note:"))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.header_note_source_field = QtGui.QComboBox(self.otherOptions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header_note_source_field.sizePolicy().hasHeightForWidth())
        self.header_note_source_field.setSizePolicy(sizePolicy)
        self.header_note_source_field.setMinimumSize(QtCore.QSize(0, 0))
        self.header_note_source_field.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.header_note_source_field.setToolTip(_("Custom column source for text to include in Description section."))
        self.header_note_source_field.setObjectName(_fromUtf8("header_note_source_field"))
        self.horizontalLayout.addWidget(self.header_note_source_field)
        self.line_4 = QtGui.QFrame(self.otherOptions)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.horizontalLayout.addWidget(self.line_4)
        self.label_10 = QtGui.QLabel(self.otherOptions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(0, 0))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_10.setText(_("&Thumb width:"))
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout.addWidget(self.label_10)
        self.thumb_width = QtGui.QDoubleSpinBox(self.otherOptions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thumb_width.sizePolicy().hasHeightForWidth())
        self.thumb_width.setSizePolicy(sizePolicy)
        self.thumb_width.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.thumb_width.setToolTip(_("Size hint for cover thumbnails included in Descriptions section."))
        self.thumb_width.setSuffix(_(" inch"))
        self.thumb_width.setDecimals(2)
        self.thumb_width.setMinimum(1.0)
        self.thumb_width.setMaximum(2.0)
        self.thumb_width.setSingleStep(0.1)
        self.thumb_width.setObjectName(_fromUtf8("thumb_width"))
        self.horizontalLayout.addWidget(self.thumb_width)
        self.gridLayout_3.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.otherOptions)
        self.label.setBuddy(self.exclude_genre)
        self.regex_results_label.setBuddy(self.exclude_genre)
        self.label_9.setBuddy(self.merge_source_field)
        self.label_3.setBuddy(self.header_note_source_field)
        self.label_10.setBuddy(self.merge_source_field)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        pass

