# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/yc/code/calibre/calibre/src/calibre/gui2/viewer/config.ui'
#
# Created: Thu Oct 25 16:54:55 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(839, 630)
        Dialog.setWindowTitle(_("Configure Ebook viewer"))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(I("config.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout_4 = QtGui.QGridLayout(Dialog)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok|QtGui.QDialogButtonBox.RestoreDefaults)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_4.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.tabs = QtGui.QTabWidget(Dialog)
        self.tabs.setObjectName(_fromUtf8("tabs"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.toolBox = QtGui.QToolBox(self.tab)
        self.toolBox.setStyleSheet(_fromUtf8("QToolBox::tab {\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                 stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"     border-radius: 5px;\n"
"     color: black;\n"
"     font-weight: bold;\n"
" }\n"
"\n"
" QToolBox::tab:selected {\n"
"     font-style: italic;\n"
" }\n"
"\n"
"QToolBox::tab:hover {\n"
"   color: red;\n"
"   font-style: italic;\n"
"}"))
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 811, 352))
        self.page.setObjectName(_fromUtf8("page"))
        self.formLayout_2 = QtGui.QFormLayout(self.page)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label = QtGui.QLabel(self.page)
        self.label.setText(_("Se&rif family:"))
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.serif_family = QtGui.QFontComboBox(self.page)
        self.serif_family.setObjectName(_fromUtf8("serif_family"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.serif_family)
        self.label_2 = QtGui.QLabel(self.page)
        self.label_2.setText(_("&Sans family:"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.sans_family = QtGui.QFontComboBox(self.page)
        self.sans_family.setObjectName(_fromUtf8("sans_family"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.sans_family)
        self.label_3 = QtGui.QLabel(self.page)
        self.label_3.setText(_("&Monospace family:"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.mono_family = QtGui.QFontComboBox(self.page)
        self.mono_family.setObjectName(_fromUtf8("mono_family"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.mono_family)
        self.label_4 = QtGui.QLabel(self.page)
        self.label_4.setText(_("&Default font size:"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.default_font_size = QtGui.QSpinBox(self.page)
        self.default_font_size.setSuffix(_(" px"))
        self.default_font_size.setMinimum(8)
        self.default_font_size.setMaximum(40)
        self.default_font_size.setObjectName(_fromUtf8("default_font_size"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.default_font_size)
        self.label_5 = QtGui.QLabel(self.page)
        self.label_5.setText(_("Monospace &font size:"))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.mono_font_size = QtGui.QSpinBox(self.page)
        self.mono_font_size.setSuffix(_(" px"))
        self.mono_font_size.setMinimum(8)
        self.mono_font_size.setMaximum(50)
        self.mono_font_size.setObjectName(_fromUtf8("mono_font_size"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.mono_font_size)
        self.label_6 = QtGui.QLabel(self.page)
        self.label_6.setText(_("S&tandard font:"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_6)
        self.standard_font = QtGui.QComboBox(self.page)
        self.standard_font.setObjectName(_fromUtf8("standard_font"))
        self.standard_font.addItem(_fromUtf8(""))
        self.standard_font.setItemText(0, _("Serif"))
        self.standard_font.addItem(_fromUtf8(""))
        self.standard_font.setItemText(1, _("Sans-serif"))
        self.standard_font.addItem(_fromUtf8(""))
        self.standard_font.setItemText(2, _("Monospace"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.standard_font)
        self.label_12 = QtGui.QLabel(self.page)
        self.label_12.setText(_("Font &magnification step size:"))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_12)
        self.opt_font_mag_step = QtGui.QSpinBox(self.page)
        self.opt_font_mag_step.setToolTip(_("The amount by which the font size is increased/decreased\n"
" when you click the font size larger/smaller buttons"))
        self.opt_font_mag_step.setSuffix(_("%"))
        self.opt_font_mag_step.setObjectName(_fromUtf8("opt_font_mag_step"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.FieldRole, self.opt_font_mag_step)
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.page_5 = QtGui.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 397, 232))
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.formLayout_5 = QtGui.QFormLayout(self.page_5)
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.label_8 = QtGui.QLabel(self.page_5)
        self.label_8.setText(_("<p>These options only apply in \"paged\" mode, where the text is broken up into pages, as in a paper book. To get into this mode, use the button with the yellow scroll icon in the top right corner of the viewer window."))
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.SpanningRole, self.label_8)
        self.label_13 = QtGui.QLabel(self.page_5)
        self.label_13.setText(_("The number of &pages of text to show on screen "))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_13)
        self.opt_cols_per_screen = QtGui.QSpinBox(self.page_5)
        self.opt_cols_per_screen.setSuffix(_(" page(s)"))
        self.opt_cols_per_screen.setMinimum(1)
        self.opt_cols_per_screen.setMaximum(5)
        self.opt_cols_per_screen.setObjectName(_fromUtf8("opt_cols_per_screen"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.opt_cols_per_screen)
        self.opt_override_book_margins = QtGui.QCheckBox(self.page_5)
        self.opt_override_book_margins.setText(_("&Override the page margin settings specified in the book"))
        self.opt_override_book_margins.setChecked(True)
        self.opt_override_book_margins.setObjectName(_fromUtf8("opt_override_book_margins"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.SpanningRole, self.opt_override_book_margins)
        self.label_18 = QtGui.QLabel(self.page_5)
        self.label_18.setText(_("&Top margin"))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_18)
        self.opt_top_margin = QtGui.QSpinBox(self.page_5)
        self.opt_top_margin.setSuffix(_(" px"))
        self.opt_top_margin.setMinimum(10)
        self.opt_top_margin.setMaximum(1000)
        self.opt_top_margin.setObjectName(_fromUtf8("opt_top_margin"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.FieldRole, self.opt_top_margin)
        self.label_19 = QtGui.QLabel(self.page_5)
        self.label_19.setText(_("&Side margin"))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout_5.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_19)
        self.opt_side_margin = QtGui.QSpinBox(self.page_5)
        self.opt_side_margin.setSuffix(_(" px"))
        self.opt_side_margin.setMinimum(10)
        self.opt_side_margin.setMaximum(1000)
        self.opt_side_margin.setObjectName(_fromUtf8("opt_side_margin"))
        self.formLayout_5.setWidget(4, QtGui.QFormLayout.FieldRole, self.opt_side_margin)
        self.label_17 = QtGui.QLabel(self.page_5)
        self.label_17.setText(_("&Bottom margin"))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout_5.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_17)
        self.opt_bottom_margin = QtGui.QSpinBox(self.page_5)
        self.opt_bottom_margin.setSuffix(_(" px"))
        self.opt_bottom_margin.setMinimum(10)
        self.opt_bottom_margin.setMaximum(1000)
        self.opt_bottom_margin.setObjectName(_fromUtf8("opt_bottom_margin"))
        self.formLayout_5.setWidget(5, QtGui.QFormLayout.FieldRole, self.opt_bottom_margin)
        self.toolBox.addItem(self.page_5, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 811, 352))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.formLayout = QtGui.QFormLayout(self.page_2)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_7 = QtGui.QLabel(self.page_2)
        self.label_7.setText(_("Maximum text width in &fullscreen:"))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.max_fs_width = QtGui.QSpinBox(self.page_2)
        self.max_fs_width.setToolTip(_("Set the maximum width that the book\'s text and pictures will take when in fullscreen mode. This allows you to read the book text without it becoming too wide."))
        self.max_fs_width.setSuffix(_(" px"))
        self.max_fs_width.setMinimum(100)
        self.max_fs_width.setMaximum(10000)
        self.max_fs_width.setObjectName(_fromUtf8("max_fs_width"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.max_fs_width)
        self.opt_fullscreen_clock = QtGui.QCheckBox(self.page_2)
        self.opt_fullscreen_clock.setText(_("Show &clock in full screen mode"))
        self.opt_fullscreen_clock.setObjectName(_fromUtf8("opt_fullscreen_clock"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.opt_fullscreen_clock)
        self.opt_fullscreen_pos = QtGui.QCheckBox(self.page_2)
        self.opt_fullscreen_pos.setText(_("Show reading &position in full screen mode"))
        self.opt_fullscreen_pos.setObjectName(_fromUtf8("opt_fullscreen_pos"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.SpanningRole, self.opt_fullscreen_pos)
        self.opt_fullscreen_scrollbar = QtGui.QCheckBox(self.page_2)
        self.opt_fullscreen_scrollbar.setText(_("Show &scrollbar in full screen mode"))
        self.opt_fullscreen_scrollbar.setObjectName(_fromUtf8("opt_fullscreen_scrollbar"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.SpanningRole, self.opt_fullscreen_scrollbar)
        self.toolBox.addItem(self.page_2, _fromUtf8(""))
        self.page_6 = QtGui.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 351, 76))
        self.page_6.setObjectName(_fromUtf8("page_6"))
        self.formLayout_6 = QtGui.QFormLayout(self.page_6)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.label_14 = QtGui.QLabel(self.page_6)
        self.label_14.setText(_("Background color:"))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_14)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.background_color_sample = QtGui.QLabel(self.page_6)
        self.background_color_sample.setText(_("Sample"))
        self.background_color_sample.setObjectName(_fromUtf8("background_color_sample"))
        self.horizontalLayout.addWidget(self.background_color_sample)
        self.change_background_color_button = QtGui.QPushButton(self.page_6)
        self.change_background_color_button.setText(_("Change"))
        self.change_background_color_button.setObjectName(_fromUtf8("change_background_color_button"))
        self.horizontalLayout.addWidget(self.change_background_color_button)
        self.reset_background_color_button = QtGui.QPushButton(self.page_6)
        self.reset_background_color_button.setText(_("Reset"))
        self.reset_background_color_button.setObjectName(_fromUtf8("reset_background_color_button"))
        self.horizontalLayout.addWidget(self.reset_background_color_button)
        self.formLayout_6.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_16 = QtGui.QLabel(self.page_6)
        self.label_16.setText(_("Text color:"))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_16)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.text_color_sample = QtGui.QLabel(self.page_6)
        self.text_color_sample.setText(_("Sample"))
        self.text_color_sample.setObjectName(_fromUtf8("text_color_sample"))
        self.horizontalLayout_2.addWidget(self.text_color_sample)
        self.change_text_color_button = QtGui.QPushButton(self.page_6)
        self.change_text_color_button.setText(_("Change"))
        self.change_text_color_button.setObjectName(_fromUtf8("change_text_color_button"))
        self.horizontalLayout_2.addWidget(self.change_text_color_button)
        self.reset_text_color_button = QtGui.QPushButton(self.page_6)
        self.reset_text_color_button.setText(_("Reset"))
        self.reset_text_color_button.setObjectName(_fromUtf8("reset_text_color_button"))
        self.horizontalLayout_2.addWidget(self.reset_text_color_button)
        self.formLayout_6.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.toolBox.addItem(self.page_6, _fromUtf8(""))
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 410, 120))
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.formLayout_3 = QtGui.QFormLayout(self.page_3)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_11 = QtGui.QLabel(self.page_3)
        self.label_11.setText(_("Page flip &duration:"))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_11)
        self.opt_page_flip_duration = QtGui.QDoubleSpinBox(self.page_3)
        self.opt_page_flip_duration.setSpecialValueText(_("disabled"))
        self.opt_page_flip_duration.setSuffix(_(" secs"))
        self.opt_page_flip_duration.setDecimals(1)
        self.opt_page_flip_duration.setMinimum(0.1)
        self.opt_page_flip_duration.setMaximum(3.0)
        self.opt_page_flip_duration.setSingleStep(0.1)
        self.opt_page_flip_duration.setProperty("value", 0.5)
        self.opt_page_flip_duration.setObjectName(_fromUtf8("opt_page_flip_duration"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.opt_page_flip_duration)
        self.opt_wheel_flips_pages = QtGui.QCheckBox(self.page_3)
        self.opt_wheel_flips_pages.setText(_("Mouse &wheel flips pages"))
        self.opt_wheel_flips_pages.setObjectName(_fromUtf8("opt_wheel_flips_pages"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.SpanningRole, self.opt_wheel_flips_pages)
        self.opt_line_scrolling_stops_on_pagebreaks = QtGui.QCheckBox(self.page_3)
        self.opt_line_scrolling_stops_on_pagebreaks.setText(_("Line &scrolling stops at page breaks"))
        self.opt_line_scrolling_stops_on_pagebreaks.setObjectName(_fromUtf8("opt_line_scrolling_stops_on_pagebreaks"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.SpanningRole, self.opt_line_scrolling_stops_on_pagebreaks)
        self.opt_fit_images = QtGui.QCheckBox(self.page_3)
        self.opt_fit_images.setText(_("&Resize images larger than the viewer window (needs restart)"))
        self.opt_fit_images.setObjectName(_fromUtf8("opt_fit_images"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.SpanningRole, self.opt_fit_images)
        self.toolBox.addItem(self.page_3, _fromUtf8(""))
        self.page_4 = QtGui.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 352, 123))
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.formLayout_4 = QtGui.QFormLayout(self.page_4)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.hyphenate = QtGui.QCheckBox(self.page_4)
        self.hyphenate.setText(_("H&yphenate (break line in the middle of large words)"))
        self.hyphenate.setObjectName(_fromUtf8("hyphenate"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.SpanningRole, self.hyphenate)
        self.hyphenate_label = QtGui.QLabel(self.page_4)
        self.hyphenate_label.setText(_("Default &language for hyphenation:"))
        self.hyphenate_label.setObjectName(_fromUtf8("hyphenate_label"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.hyphenate_label)
        self.hyphenate_default_lang = QtGui.QComboBox(self.page_4)
        self.hyphenate_default_lang.setToolTip(_("The default language to use for hyphenation rules. If the book does not specify a language, this will be used."))
        self.hyphenate_default_lang.setObjectName(_fromUtf8("hyphenate_default_lang"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.hyphenate_default_lang)
        self.opt_remember_window_size = QtGui.QCheckBox(self.page_4)
        self.opt_remember_window_size.setText(_("Remember last used &window size and layout"))
        self.opt_remember_window_size.setObjectName(_fromUtf8("opt_remember_window_size"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.SpanningRole, self.opt_remember_window_size)
        self.opt_remember_current_page = QtGui.QCheckBox(self.page_4)
        self.opt_remember_current_page.setText(_("Remember the &current page when quitting"))
        self.opt_remember_current_page.setObjectName(_fromUtf8("opt_remember_current_page"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.SpanningRole, self.opt_remember_current_page)
        self.toolBox.addItem(self.page_4, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.toolBox)
        self.tabs.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_9 = QtGui.QLabel(self.tab_2)
        self.label_9.setText(_("Double click to change a keyboard shortcut"))
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout.addWidget(self.label_9)
        self.tabs.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_10 = QtGui.QLabel(self.tab_3)
        self.label_10.setText(_("<p>A CSS stylesheet that can be used to control the look and feel of books. For examples, click <a href=\"http://www.mobileread.com/forums/showthread.php?t=51500\">here</a>."))
        self.label_10.setWordWrap(True)
        self.label_10.setOpenExternalLinks(True)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_3.addWidget(self.label_10)
        self.css = QtGui.QPlainTextEdit(self.tab_3)
        self.css.setObjectName(_fromUtf8("css"))
        self.verticalLayout_3.addWidget(self.css)
        self.tabs.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.formLayout_7 = QtGui.QFormLayout(self.tab_4)
        self.formLayout_7.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_7.setObjectName(_fromUtf8("formLayout_7"))
        self.label_23 = QtGui.QLabel(self.tab_4)
        self.label_23.setText(_("You can save and load the viewer settings as <i>themes</i>"))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.SpanningRole, self.label_23)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_7.setItem(1, QtGui.QFormLayout.LabelRole, spacerItem)
        self.label_15 = QtGui.QLabel(self.tab_4)
        self.label_15.setText(_("Save current settings as a theme:"))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_15)
        self.save_theme_button = QtGui.QToolButton(self.tab_4)
        self.save_theme_button.setText(_("&Save"))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(I("save.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_theme_button.setIcon(icon1)
        self.save_theme_button.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.save_theme_button.setObjectName(_fromUtf8("save_theme_button"))
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.FieldRole, self.save_theme_button)
        self.label_20 = QtGui.QLabel(self.tab_4)
        self.label_20.setText(_("Load a previously saved theme:"))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.formLayout_7.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_20)
        self.load_theme_button = QtGui.QToolButton(self.tab_4)
        self.load_theme_button.setText(_("&Load"))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(I("document_open.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.load_theme_button.setIcon(icon2)
        self.load_theme_button.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.load_theme_button.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.load_theme_button.setObjectName(_fromUtf8("load_theme_button"))
        self.formLayout_7.setWidget(4, QtGui.QFormLayout.FieldRole, self.load_theme_button)
        self.label_21 = QtGui.QLabel(self.tab_4)
        self.label_21.setText(_("Delete a saved theme:"))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.formLayout_7.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_21)
        self.delete_theme_button = QtGui.QToolButton(self.tab_4)
        self.delete_theme_button.setText(_("&Delete"))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(I("trash.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_theme_button.setIcon(icon3)
        self.delete_theme_button.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.delete_theme_button.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.delete_theme_button.setObjectName(_fromUtf8("delete_theme_button"))
        self.formLayout_7.setWidget(5, QtGui.QFormLayout.FieldRole, self.delete_theme_button)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_7.setItem(6, QtGui.QFormLayout.FieldRole, spacerItem1)
        self.theming_message = QtGui.QLabel(self.tab_4)
        self.theming_message.setText(_fromUtf8(""))
        self.theming_message.setObjectName(_fromUtf8("theming_message"))
        self.formLayout_7.setWidget(7, QtGui.QFormLayout.SpanningRole, self.theming_message)
        self.tabs.addTab(self.tab_4, _fromUtf8(""))
        self.gridLayout_4.addWidget(self.tabs, 0, 0, 1, 1)
        self.label.setBuddy(self.serif_family)
        self.label_2.setBuddy(self.sans_family)
        self.label_3.setBuddy(self.mono_family)
        self.label_4.setBuddy(self.default_font_size)
        self.label_5.setBuddy(self.mono_font_size)
        self.label_6.setBuddy(self.standard_font)
        self.label_12.setBuddy(self.opt_font_mag_step)
        self.label_13.setBuddy(self.opt_cols_per_screen)
        self.label_18.setBuddy(self.opt_top_margin)
        self.label_19.setBuddy(self.opt_side_margin)
        self.label_17.setBuddy(self.opt_bottom_margin)
        self.label_7.setBuddy(self.max_fs_width)
        self.label_11.setBuddy(self.opt_page_flip_duration)
        self.hyphenate_label.setBuddy(self.hyphenate_default_lang)
        self.label_15.setBuddy(self.save_theme_button)
        self.label_20.setBuddy(self.load_theme_button)

        self.retranslateUi(Dialog)
        self.tabs.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QObject.connect(self.hyphenate, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.hyphenate_default_lang.setEnabled)
        QtCore.QObject.connect(self.opt_override_book_margins, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.opt_top_margin.setEnabled)
        QtCore.QObject.connect(self.opt_override_book_margins, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.opt_side_margin.setEnabled)
        QtCore.QObject.connect(self.opt_override_book_margins, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.opt_bottom_margin.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _("&Font options"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), _("Text &layout in paged mode"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _("F&ull  screen options"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_6), _("Colors and backgrounds"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _("Page Fl&ip options"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _("&Miscellaneous options"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab), _("&General"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_2), _("&Keyboard shortcuts"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_3), _("User &Stylesheet"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_4), _("&Theming"))


